CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE TABLE "SearchQueries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Keyword" character varying(500) NOT NULL,
        "Category" character varying(200),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SearchQueries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE TABLE "FoundTenders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" character varying(200) NOT NULL,
        "PurchaseNumber" character varying(200) NOT NULL,
        "Title" character varying(1000) NOT NULL,
        "CustomerName" character varying(500),
        "PublishDate" timestamp with time zone,
        "DirectLinkToSource" character varying(1000),
        "FoundByQueryId" integer,
        "SavedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FoundTenders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FoundTenders_SearchQueries_FoundByQueryId" FOREIGN KEY ("FoundByQueryId") REFERENCES "SearchQueries" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_FoundTenders_ExternalId" ON "FoundTenders" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE INDEX "IX_FoundTenders_FoundByQueryId" ON "FoundTenders" ("FoundByQueryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE INDEX "IX_FoundTenders_PublishDate" ON "FoundTenders" ("PublishDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE INDEX "IX_FoundTenders_SavedAt" ON "FoundTenders" ("SavedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE INDEX "IX_SearchQueries_CreatedAt" ON "SearchQueries" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    CREATE INDEX "IX_SearchQueries_IsActive" ON "SearchQueries" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260124000015_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260124000015_InitialCreate', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    ALTER TABLE "FoundTenders" ADD "AdditionalInfo" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    ALTER TABLE "FoundTenders" ADD "ApplicationDeadline" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    ALTER TABLE "FoundTenders" ADD "CustomerInn" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    ALTER TABLE "FoundTenders" ADD "MaxPrice" numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    ALTER TABLE "FoundTenders" ADD "Region" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125235128_AddApplicationDeadlineFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260125235128_AddApplicationDeadlineFields', '10.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE TABLE "TenderDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenderId" integer NOT NULL,
        "DocType" character varying(100) NOT NULL,
        "PublishedAt" timestamp with time zone,
        "DownloadedAt" timestamp with time zone NOT NULL,
        "SourceJson" jsonb NOT NULL,
        "FilePath" character varying(500),
        CONSTRAINT "PK_TenderDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TenderDocuments_FoundTenders_TenderId" FOREIGN KEY ("TenderId") REFERENCES "FoundTenders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE TABLE "TechnologyAnalyses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenderId" integer NOT NULL,
        "MatchScore" integer NOT NULL,
        "MatchedTechnologiesJson" jsonb NOT NULL,
        "IsCompatible" boolean NOT NULL,
        "AnalyzedAt" timestamp with time zone NOT NULL,
        "AnalysisNotes" character varying(2000),
        "ManuallyVerified" boolean NOT NULL,
        "DocumentId" integer,
        CONSTRAINT "PK_TechnologyAnalyses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TechnologyAnalyses_FoundTenders_TenderId" FOREIGN KEY ("TenderId") REFERENCES "FoundTenders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TechnologyAnalyses_TenderDocuments_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "TenderDocuments" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TechnologyAnalyses_AnalyzedAt" ON "TechnologyAnalyses" ("AnalyzedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE UNIQUE INDEX "IX_TechnologyAnalyses_DocumentId" ON "TechnologyAnalyses" ("DocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TechnologyAnalyses_IsCompatible" ON "TechnologyAnalyses" ("IsCompatible");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TechnologyAnalyses_ManuallyVerified" ON "TechnologyAnalyses" ("ManuallyVerified");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TechnologyAnalyses_MatchScore" ON "TechnologyAnalyses" ("MatchScore");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TechnologyAnalyses_TenderId" ON "TechnologyAnalyses" ("TenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TenderDocuments_DocType" ON "TenderDocuments" ("DocType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TenderDocuments_DownloadedAt" ON "TenderDocuments" ("DownloadedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TenderDocuments_PublishedAt" ON "TenderDocuments" ("PublishedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    CREATE INDEX "IX_TenderDocuments_TenderId" ON "TenderDocuments" ("TenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260128011519_AddDocumentAndAnalysisModels') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260128011519_AddDocumentAndAnalysisModels', '10.0.2');
    END IF;
END $EF$;
COMMIT;

