// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenderTracker.API.Data;

#nullable disable

namespace TenderTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131145724_AddNotificationSettings")]
    partial class AddNotificationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenderTracker.API.Models.FoundTender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerInn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DirectLinkToSource")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("FoundByQueryId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanNumbersJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("FoundByQueryId");

                    b.HasIndex("PublishDate");

                    b.HasIndex("SavedAt");

                    b.ToTable("FoundTenders");
                });

            modelBuilder.Entity("TenderTracker.API.Models.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeadlineWarningDays")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilterCriteriaJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NotifyOnDeadlineApproaching")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnNewTenders")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnTechnologyMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NotificationType");

                    b.HasIndex("NotifyOnDeadlineApproaching");

                    b.HasIndex("NotifyOnNewTenders");

                    b.HasIndex("NotifyOnTechnologyMatch");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("TenderTracker.API.Models.SearchQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.ToTable("SearchQueries");
                });

            modelBuilder.Entity("TenderTracker.API.Models.TechnologyAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManuallyVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedTechnologiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("IsCompatible");

                    b.HasIndex("ManuallyVerified");

                    b.HasIndex("MatchScore");

                    b.HasIndex("TenderId");

                    b.ToTable("TechnologyAnalyses");
                });

            modelBuilder.Entity("TenderTracker.API.Models.TenderDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocType");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderDocuments");
                });

            modelBuilder.Entity("TenderTracker.API.Models.FoundTender", b =>
                {
                    b.HasOne("TenderTracker.API.Models.SearchQuery", "FoundByQuery")
                        .WithMany("FoundTenders")
                        .HasForeignKey("FoundByQueryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FoundByQuery");
                });

            modelBuilder.Entity("TenderTracker.API.Models.TechnologyAnalysis", b =>
                {
                    b.HasOne("TenderTracker.API.Models.TenderDocument", "Document")
                        .WithOne("TechnologyAnalysis")
                        .HasForeignKey("TenderTracker.API.Models.TechnologyAnalysis", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TenderTracker.API.Models.FoundTender", "Tender")
                        .WithMany("TechnologyAnalyses")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderTracker.API.Models.TenderDocument", b =>
                {
                    b.HasOne("TenderTracker.API.Models.FoundTender", "Tender")
                        .WithMany("Documents")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderTracker.API.Models.FoundTender", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("TechnologyAnalyses");
                });

            modelBuilder.Entity("TenderTracker.API.Models.SearchQuery", b =>
                {
                    b.Navigation("FoundTenders");
                });

            modelBuilder.Entity("TenderTracker.API.Models.TenderDocument", b =>
                {
                    b.Navigation("TechnologyAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
